server:
  port: 9002
spring:
 config:
   import:
    - optional:configserver:http://localhost:8088
 profiles:
    active:
    - qa
 application:
    name: rating-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka, http://localhost:8901/eureka